drop table if exists gather;
CREATE TABLE `gather` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`title` varchar(255) NOT NULL COMMENT '标题',
`typeid` tinyint(4) DEFAULT NULL,
`grade` varchar(10) DEFAULT NULL COMMENT '评分值',
`litpic` varchar(255) DEFAULT NULL COMMENT '缩略图',
`con_url` varchar(255) NOT NULL DEFAULT '' COMMENT '内容页地址',
`body` text NOT NULL COMMENT '描述',
`director` varchar(50) DEFAULT NULL COMMENT '导演,只有一位',
`actors` varchar(255) DEFAULT NULL COMMENT '主演有多个,以逗号分隔',
`myear` varchar(20) DEFAULT NULL COMMENT '影片上映年份',
`lan_guage` varchar(50) DEFAULT NULL COMMENT '影片语言',
`types` varchar(255) DEFAULT NULL COMMENT '类别信息,以逗号分隔',
`down_link` longtext COMMENT '下载链接,以逗号分隔',
`is_litpic` tinyint(2) NOT NULL DEFAULT '-1' COMMENT '是否下载图片',
`is_con` tinyint(2) NOT NULL DEFAULT '-1' COMMENT '是否下载内容页,-1没有,0提交',
`is_body` tinyint(2) DEFAULT '-1' COMMENT '内容页图片是否下载',
`is_douban` tinyint(4) DEFAULT '-1' COMMENT '是否运行过豆瓣程序,默认为1,否则为0',
`is_post` tinyint(4) NOT NULL DEFAULT '-1' COMMENT '是否已经提交到dede后台',
`episode_nums` smallint(6) NOT NULL DEFAULT '0' COMMENT '电视剧的总集数',
`m_time` timestamp NULL DEFAULT NULL COMMENT '影片网站上更新的时间,通过这个时间去判断是否需要更新',
PRIMARY KEY (`id`),
KEY `idx_is_con` (`is_con`),
KEY `idx_is_litpic` (`is_litpic`) USING BTREE,
KEY `idx_title` (`title`),
KEY `idx_typeid` (`typeid`),
KEY `idx_is_body` (`is_body`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=10946 DEFAULT CHARSET=utf8;